plugins:
  - jekyll-redirect-from


title: My Resume
url: 'http://bertrandbenjamin.com'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#default          # Blue
#style: styles-2  # LightBlue
#style: styles-3  # Green
#style: styles-4  # Pink
#style: styles-5  # Orange
#style: styles-6  # GreyBlue


#Profile information
name: Benjamin Bertrand
tagline: Full Stack Java developer with interests in Big Data & Machine learning
pic: avatar.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
address:
#  street: Streety
  postalCode: 44100
  locality: Nantes
  country: France

#sidebar links
email: bertrandbenj@gmail.com
#phone: 012 345 6789
website: bertrandbenjamin.com/ #do not add http://
linkedin: BnimajneB
github: bertrandbenj
google: +BenjaminBertrandDev


# Tracker
analytics: UA-103630400-1
#Update all the sections by editing the files inside _includes folder.
